name: Plan

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Plan Changes
    runs-on: ubuntu-latest
    if: github.actor == 'maxexcloo'
    
    env:
      # Minimal secrets - only what's absolutely required
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.4
          
          
      - name: Initialize Infrastructure
        run: |
          cd infrastructure
          tofu init -no-color
          
      - name: Plan Infrastructure
        id: plan-infra
        run: |
          cd infrastructure
          tofu plan -no-color -detailed-exitcode | tee plan-output.txt || echo "exitcode=$?" >> $GITHUB_OUTPUT
          
      - name: Initialize Services
        run: |
          cd services
          tofu init -no-color
          
      - name: Plan Services
        id: plan-services
        run: |
          cd services
          tofu plan -no-color -detailed-exitcode | tee plan-output.txt || echo "exitcode=$?" >> $GITHUB_OUTPUT
          
      - name: Upload Plan Outputs
        uses: actions/upload-artifact@v4
        with:
          name: plan-outputs-${{ github.run_id }}
          path: |
            infrastructure/plan-output.txt
            services/plan-output.txt
          retention-days: 7
          
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## OpenTofu Plan Results
            
            Infrastructure: ${{ steps.plan-infra.outputs.exitcode == '2' && '✅ Changes detected' || '✔️ No changes' }}
            Services: ${{ steps.plan-services.outputs.exitcode == '2' && '✅ Changes detected' || '✔️ No changes' }}
            
            Plan outputs have been uploaded as artifacts.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });